condense and re-work cmplx scripts and rebrand them to vanir

diff --git a/system/etc/init.d/98vanir b/system/etc/init.d/98vanir
--- a/system/etc/init.d/98vanir
+++ b/system/etc/init.d/98vanir
@@ -7,7 +7,7 @@ if [ -e $LOG_FILE ]; then
 	rm $LOG_FILE;
 fi;
 
-#knuckleheads, gain rw access
+# gain rw access
 sysrw
 
 # enable sysctl tweaks
@@ -109,21 +109,121 @@ busybox mount -o remount,noatime,nodiratime,discard,noauto_da_alloc,nosuid,nodev
 busybox mount -o remount,noatime,nodiratime,discard,noauto_da_alloc,nosuid,nodev,data=writeback,barrier=0 -t auto /mnt/obb
 busybox mount -o remount,noatime,nodiratime,discard,noauto_da_alloc,nosuid,nodev,data=writeback,barrier=0 -t auto /mnt/sdcard
 
+#Defrags database files
+
+VAC_LOG_FILE=/data/S50-vacuum-databases.log
+
+# do nothing if less than 5 days
+find $VAC_LOG_FILE -type f -mtime +5 -delete
+
+if ! test -f $VAC_LOG_FILE; then
+
+	/bin/mount -o remount,rw /
+
+	if [ -e $VAC_LOG_FILE ]; then
+		rm $VAC_LOG_FILE;
+	fi;
+    	
+	echo "Starting Sqlite Vacuum $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $VAC_LOG_FILE;
+
+	for i in \
+	`find /data -iname "*.db"`
+	do \
+		sqlite3 $i 'VACUUM;'; 
+		echo Vacuum $i  | tee -a $VAC_LOG_FILE;
+	done;
+
+	for i in \
+	`find /dbdata -iname "*.db"`
+	do \
+		sqlite3 $i 'VACUUM;'; 
+		echo Vacuum $i  | tee -a $VAC_LOG_FILE;
+	done;
+
+	for i in \
+	`find /sdcard -iname "*.db"`
+	do \
+		sqlite3 $i 'VACUUM;'; 
+		echo Vacuum $i  | tee -a $VAC_LOG_FILE;
+	done
+
+	echo "Sqlite Vacuum finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $VAC_LOG_FILE;
+
+	/bin/mount -o remount,ro /
+
+fi
+
+# CMPLX zipalign.
+
+
+ZIP_LOG_FILE=/data/log/zipalign.log;
+ZIPALIGNED_APK=/data/local/zipalignedapk;
+
+if [ -e $ZIP_LOG_FILE ]; then
+	rm $ZIP_LOG_FILE;
+fi;
+
+if [ ! -f $ZIPALIGNED_APK ]; then
+	touch $ZIPALIGNED_APK;
+fi;
+
+echo "Automatic ZipAlign started at $( date +"%m-%d-%Y %H:%M:%S" ) " | tee -a $ZiP_LOG_FILE;
+
+for DIR in /system/app /data/app; do
+	cd $DIR;
+	for APK in *.apk; do
+		if [ $APK -ot $ZIPALIGNED_APK ] && [ $(grep "$DIR/$APK" $ZIPALIGNED_APK|wc -l) -gt 0 ]; then
+			echo "Already checked: $DIR/$APK" | tee -a $ZIP_LOG_FILE;
+			if [ -e /data/$APK ]; then
+				rm /data/$APK;
+				echo "Temporary APK removed: /data/$APK" | tee -a $ZIP_LOG_FILE;
+			fi;
+		else
+			ZIPCHECK=`/system/xbin/zipalign -c -v 4 $APK | grep FAILED | wc -l`;
+			if [ $ZIPCHECK == "1" ]; then
+				echo "Now aligning: $DIR/$APK" | tee -a $ZIP_LOG_FILE;
+				/system/xbin/zipalign -v -f 4 $APK /data/$APK;
+				sync
+				busybox mount -o rw,remount /system;
+				cp -f -p /data/$APK $APK;
+				rm /data/$APK;
+				if [ -e /data/$APK ]; then
+					sleep 2;
+					rm /data/$APK;
+					if [ -e /data/$APK ]; then
+						echo "Failed to remove APK. Run the tweak again : /data/$APK" | tee -a $ZIP_LOG_FILE;
+					else
+						echo "Temporary APK removed: /data/$APK" | tee -a $ZIP_LOG_FILE;
+					fi;
+				fi;
+				grep "$DIR/$APK" $ZIPALIGNED_APK > /dev/null || echo $DIR/$APK >> $ZIPALIGNED_APK;
+			else
+				echo "Already aligned: $DIR/$APK" | tee -a $ZIP_LOG_FILE;
+				if [ -e /data/$APK ]; then
+					rm /data/$APK;
+					echo "Temporary APK removed: /data/$APK" | tee -a $ZIP_LOG_FILE;
+				fi;
+				grep "$DIR/$APK" $ZIPALIGNED_APK > /dev/null || echo $DIR/$APK >> $ZIPALIGNED_APK;
+			fi;
+		fi;
+	done;
+done;
+sync
+busybox mount -o ro,remount /system;
+touch $ZIPALIGNED_APK;
+echo "Automatic ZipAlign finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $ZIP_LOG_FILE;
+
 #set renice credit Prime Directive
 #tweaked by Sonicxml
 # Fixed by jdk
 #
 renice -15 `pidof com.android.launcher`
-renice -12 `pidof com.android.chrome`
 renice -12 `pidof com.google.android.browser`
 renice -10 `pidof com.android.phone`
 renice -10 `pidof com.android.systemui`
 renice -8 `pidof com.android.settings`
-renice -8 `pidof com.android.vending`
-renice -7 `pidof com.android.inputmethod.latin`
 renice -6 `pidof com.android.camera`
 renice -6 `pidof com.google.android.apps.maps`
-ionice -c3 -n7 `pidof com.swype.android.inputmethd:swypeconnect`
 ionice -c2 -n0 `pidof com.android.camera`
 
 busybox rm -f /data/system/userbehavior.db
